# Set to author to set pr creator as assignee
addAssignees: author

# A list of users to be skipped by both the add reviewers and add assignees processes
skipUsers:
  - dependabot[bot]

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
