name: Update seminars
on:
  issues:
    types: [opened, edited]
jobs:
  update-seminars:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p build/
      - run: python3 scripts/update-seminars.py > build/index.md