name: Update seminars
on:
  issues:
    types: [opened, edited]
  push:
    branches:
      - main
  pull_request:

jobs:
  update-seminars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          pip install python-dateutil  # Yes, it is different from the import name
          mkdir -p build/
          
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python3 scripts/update-seminars.py > build/index.md
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          enable_jekyll: true